
package com.pronetbeans.examples;

import com.sun.speech.freetts.Voice;
import com.sun.speech.freetts.VoiceManager;

/**
 *
 * @author  Adam Myatt
 */
public class SayIt extends javax.swing.JFrame {

    /** Creates new form SayIt */
    public SayIt() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TextToBeSpoken = new javax.swing.JTextArea();
        SpeakTextButton = new javax.swing.JButton();
        ClearTextButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TextToBeSpoken.setColumns(20);
        TextToBeSpoken.setRows(5);
        TextToBeSpoken.setToolTipText("Enter text to be spoken here.");
        jScrollPane1.setViewportView(TextToBeSpoken);

        SpeakTextButton.setText("Speak Text");
        SpeakTextButton.setToolTipText("Click to hear the text in the text area spoken.");
        SpeakTextButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SpeakTextButtonMouseClicked(evt);
            }
        });
        SpeakTextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SpeakTextButtonActionPerformed(evt);
            }
        });

        ClearTextButton.setText("Clear Text");
        ClearTextButton.setToolTipText("Click to clear the text from the text area.");
        ClearTextButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ClearTextButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(SpeakTextButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ClearTextButton)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SpeakTextButton)
                    .addComponent(ClearTextButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents




    private void SpeakTextButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SpeakTextButtonMouseClicked
        String sText = TextToBeSpoken.getText();
        if (sText != null && sText.trim().length() > 0) {
            VoiceManager voiceManager = null;
            Voice syntheticVoice = null;

            try {
                voiceManager = VoiceManager.getInstance();
                syntheticVoice = voiceManager.getVoice("kevin");
                syntheticVoice.allocate();
                syntheticVoice.speak(sText);

            } catch (Exception e) {
                e.printStackTrace();
            } finally {
                syntheticVoice.deallocate();
            }
        }
}//GEN-LAST:event_SpeakTextButtonMouseClicked

    private void ClearTextButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClearTextButtonMouseClicked
        TextToBeSpoken.setText("");
    }//GEN-LAST:event_ClearTextButtonMouseClicked

    private void SpeakTextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SpeakTextButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SpeakTextButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new SayIt().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ClearTextButton;
    private javax.swing.JButton SpeakTextButton;
    private javax.swing.JTextArea TextToBeSpoken;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
